config/routes.rb
Rails.application.routes.draw do
  resources :hooplahs
  resources :vacation_spots

  root to: "vacation_spots#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hooplah.rb
class Hooplah < ApplicationRecord
  belongs_to :vacation_spot
end

app/models/vacation_spot.rb
class VacationSpot < ApplicationRecord
  has_many :hooplahs
end

app/models/vacation_spot_observer.rb
class VacationSpotObserver < ActiveRecord::Observer
  def after_create(vacation_spot)
    Hooplah.create(
      vacation_spot_id: vacation_spot.id,
      description: "They sicken of the calm who know the storm of #{vacation_spot.name}!!!"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hooplahs_controller.rb
class HooplahsController < ApplicationController
  before_action :set_hooplah, only: [:show, :edit, :update, :destroy]

  # GET /hooplahs
  # GET /hooplahs.json
  def index
    @hooplahs = Hooplah.all
  end

  # GET /hooplahs/1
  # GET /hooplahs/1.json
  def show
  end

  # GET /hooplahs/new
  def new
    @hooplah = Hooplah.new
  end

  # GET /hooplahs/1/edit
  def edit
  end

  # POST /hooplahs
  # POST /hooplahs.json
  def create
    @hooplah = Hooplah.new(hooplah_params)

    respond_to do |format|
      if @hooplah.save
        format.html { redirect_to @hooplah, notice: 'Hooplah was successfully created.' }
        format.json { render :show, status: :created, location: @hooplah }
      else
        format.html { render :new }
        format.json { render json: @hooplah.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hooplahs/1
  # PATCH/PUT /hooplahs/1.json
  def update
    respond_to do |format|
      if @hooplah.update(hooplah_params)
        format.html { redirect_to @hooplah, notice: 'Hooplah was successfully updated.' }
        format.json { render :show, status: :ok, location: @hooplah }
      else
        format.html { render :edit }
        format.json { render json: @hooplah.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hooplahs/1
  # DELETE /hooplahs/1.json
  def destroy
    @hooplah.destroy
    respond_to do |format|
      format.html { redirect_to hooplahs_url, notice: 'Hooplah was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hooplah
      @hooplah = Hooplah.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hooplah_params
      params.require(:hooplah).permit(:vacation_spot_id, :description)
    end
end

app/controllers/vacation_spots_controller.rb
class VacationSpotsController < ApplicationController
  before_action :set_vacation_spot, only: [:show, :edit, :update, :destroy]

  # GET /vacation_spots
  # GET /vacation_spots.json
  def index
    @vacation_spots = VacationSpot.all
  end

  # GET /vacation_spots/1
  # GET /vacation_spots/1.json
  def show
  end

  # GET /vacation_spots/new
  def new
    @vacation_spot = VacationSpot.new
  end

  # GET /vacation_spots/1/edit
  def edit
  end

  # POST /vacation_spots
  # POST /vacation_spots.json
  def create
    @vacation_spot = VacationSpot.new(vacation_spot_params)

    respond_to do |format|
      if @vacation_spot.save
        format.html { redirect_to @vacation_spot, notice: 'Vacation spot was successfully created.' }
        format.json { render :show, status: :created, location: @vacation_spot }
      else
        format.html { render :new }
        format.json { render json: @vacation_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacation_spots/1
  # PATCH/PUT /vacation_spots/1.json
  def update
    respond_to do |format|
      if @vacation_spot.update(vacation_spot_params)
        format.html { redirect_to @vacation_spot, notice: 'Vacation spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation_spot }
      else
        format.html { render :edit }
        format.json { render json: @vacation_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacation_spots/1
  # DELETE /vacation_spots/1.json
  def destroy
    @vacation_spot.destroy
    respond_to do |format|
      format.html { redirect_to vacation_spots_url, notice: 'Vacation spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation_spot
      @vacation_spot = VacationSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_spot_params
      params.require(:vacation_spot).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hooplahs_helper.rb
module HooplahsHelper
end

app/helpers/vacation_spots_helper.rb
module VacationSpotsHelper
end

app/views/hooplahs/_form.html.erb
<%= form_for(hooplah) do |f| %>
  <% if hooplah.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hooplah.errors.count, "error") %> prohibited this hooplah from being saved:</h2>

      <ul>
      <% hooplah.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vacation_spot_id %>
    <%= f.number_field :vacation_spot_id %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hooplahs/edit.html.erb
<h1>Editing Hooplah</h1>

<%= render 'form', hooplah: @hooplah %>

<%= link_to 'Show', @hooplah %> |
<%= link_to 'Back', hooplahs_path %>

app/views/hooplahs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hooplahs</h1>

<table>
  <thead>
    <tr>
      <th>Vacation spot</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hooplahs.each do |hooplah| %>
      <tr>
        <td><%= hooplah.vacation_spot_id %></td>
        <td><%= hooplah.description %></td>
        <td><%= link_to 'Show', hooplah %></td>
        <td><%= link_to 'Edit', edit_hooplah_path(hooplah) %></td>
        <td><%= link_to 'Destroy', hooplah, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hooplah', new_hooplah_path %>

app/views/hooplahs/new.html.erb
<h1>New Hooplah</h1>

<%= render 'form', hooplah: @hooplah %>

<%= link_to 'Back', hooplahs_path %>

app/views/hooplahs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vacation spot:</strong>
  <%= @hooplah.vacation_spot_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hooplah.description %>
</p>

<%= link_to 'Edit', edit_hooplah_path(@hooplah) %> |
<%= link_to 'Back', hooplahs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activemodelobservernottriggering</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>There is currently <%= Hooplah.count %> much hooplah</p>
    <%= yield %>
  </body>
</html>

app/views/vacation_spots/_form.html.erb
<%= form_for(vacation_spot) do |f| %>
  <% if vacation_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacation_spot.errors.count, "error") %> prohibited this vacation_spot from being saved:</h2>

      <ul>
      <% vacation_spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacation_spots/edit.html.erb
<h1>Editing Vacation Spot</h1>

<%= render 'form', vacation_spot: @vacation_spot %>

<%= link_to 'Show', @vacation_spot %> |
<%= link_to 'Back', vacation_spots_path %>

app/views/vacation_spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacation Spots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacation_spots.each do |vacation_spot| %>
      <tr>
        <td><%= vacation_spot.name %></td>
        <td><%= link_to 'Show', vacation_spot %></td>
        <td><%= link_to 'Edit', edit_vacation_spot_path(vacation_spot) %></td>
        <td><%= link_to 'Destroy', vacation_spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation Spot', new_vacation_spot_path %>

app/views/vacation_spots/new.html.erb
<h1>New Vacation Spot</h1>

<%= render 'form', vacation_spot: @vacation_spot %>

<%= link_to 'Back', vacation_spots_path %>

app/views/vacation_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vacation_spot.name %>
</p>

<%= link_to 'Edit', edit_vacation_spot_path(@vacation_spot) %> |
<%= link_to 'Back', vacation_spots_path %>